import 'package:islami_app_c15_sun_7pm/models/sura_data_model.dart';

abstract class Constants {

  static List<SuraDataModel> kSuraData = [
    SuraDataModel(
      suraID: "1",
      suraNameAR: "الفاتحه",
      suraNameEN: "Al-Fatiha",
      suraVersesNumber: "7",
    ),
    SuraDataModel(
      suraID: "2",
      suraNameAR: "البقرة",
      suraNameEN: "Al-Baqarah",
      suraVersesNumber: "286",
    ),
    SuraDataModel(
      suraID: "3",
      suraNameAR: "آل عمران",
      suraNameEN: "Aal-E-Imran",
      suraVersesNumber: "200",
    ),
    SuraDataModel(
      suraID: "4",
      suraNameAR: "النساء",
      suraNameEN: "An-Nisa'",
      suraVersesNumber: "176",
    ),
    SuraDataModel(
      suraID: "5",
      suraNameAR: "المائدة",
      suraNameEN: "Al-Ma'idah",
      suraVersesNumber: "120",
    ),
    SuraDataModel(
      suraID: "6",
      suraNameAR: "الأنعام",
      suraNameEN: "Al-An'am",
      suraVersesNumber: "165",
    ),
    SuraDataModel(
      suraID: "7",
      suraNameAR: "الأعراف",
      suraNameEN: "Al-A'raf",
      suraVersesNumber: "206",
    ),
    SuraDataModel(
      suraID: "8",
      suraNameAR: "الأنفال",
      suraNameEN: "Al-Anfal",
      suraVersesNumber: "75",
    ),
    SuraDataModel(
      suraID: "9",
      suraNameAR: "التوبة",
      suraNameEN: "At-Tawbah",
      suraVersesNumber: "129",
    ),
    SuraDataModel(
      suraID: "10",
      suraNameAR: "يونس",
      suraNameEN: "Yunus",
      suraVersesNumber: "109",
    ),
    SuraDataModel(
      suraID: "11",
      suraNameAR: "هود",
      suraNameEN: "Hud",
      suraVersesNumber: "123",
    ),
    SuraDataModel(
      suraID: "12",
      suraNameAR: "يوسف",
      suraNameEN: "Yusuf",
      suraVersesNumber: "111",
    ),
    SuraDataModel(
      suraID: "13",
      suraNameAR: "الرعد",
      suraNameEN: "Ar-Ra'd",
      suraVersesNumber: "43",
    ),
    SuraDataModel(
      suraID: "14",
      suraNameAR: "إبراهيم",
      suraNameEN: "Ibrahim",
      suraVersesNumber: "52",
    ),
    SuraDataModel(
      suraID: "15",
      suraNameAR: "الحجر",
      suraNameEN: "Al-Hijr",
      suraVersesNumber: "99",
    ),
    SuraDataModel(
      suraID: "16",
      suraNameAR: "النحل",
      suraNameEN: "An-Nahl",
      suraVersesNumber: "128",
    ),
    SuraDataModel(
      suraID: "17",
      suraNameAR: "الإسراء",
      suraNameEN: "Al-Isra",
      suraVersesNumber: "111",
    ),
    SuraDataModel(
      suraID: "18",
      suraNameAR: "الكهف",
      suraNameEN: "Al-Kahf",
      suraVersesNumber: "110",
    ),
    SuraDataModel(
      suraID: "19",
      suraNameAR: "مريم",
      suraNameEN: "Maryam",
      suraVersesNumber: "98",
    ),
    SuraDataModel(
      suraID: "20",
      suraNameAR: "طه",
      suraNameEN: "Ta-Ha",
      suraVersesNumber: "135",
    ),
    SuraDataModel(
      suraID: "21",
      suraNameAR: "الأنبياء",
      suraNameEN: "Al-Anbiya",
      suraVersesNumber: "112",
    ),
    SuraDataModel(
      suraID: "22",
      suraNameAR: "الحج",
      suraNameEN: "Al-Hajj",
      suraVersesNumber: "78",
    ),
    SuraDataModel(
      suraID: "23",
      suraNameAR: "المؤمنون",
      suraNameEN: "Al-Mu'minun",
      suraVersesNumber: "118",
    ),
    SuraDataModel(
      suraID: "24",
      suraNameAR: "النّور",
      suraNameEN: "An-Nur",
      suraVersesNumber: "64",
    ),
    SuraDataModel(
      suraID: "25",
      suraNameAR: "الفرقان",
      suraNameEN: "Al-Furqan",
      suraVersesNumber: "77",
    ),
    SuraDataModel(
      suraID: "26",
      suraNameAR: "الشعراء",
      suraNameEN: "Ash-Shu'ara",
      suraVersesNumber: "227",
    ),
    SuraDataModel(
      suraID: "27",
      suraNameAR: "النّمل",
      suraNameEN: "An-Naml",
      suraVersesNumber: "93",
    ),
    SuraDataModel(
      suraID: "28",
      suraNameAR: "القصص",
      suraNameEN: "Al-Qasas",
      suraVersesNumber: "88",
    ),
    SuraDataModel(
      suraID: "29",
      suraNameAR: "العنكبوت",
      suraNameEN: "Al-Ankabut",
      suraVersesNumber: "69",
    ),
    SuraDataModel(
      suraID: "30",
      suraNameAR: "الرّوم",
      suraNameEN: "Ar-Rum",
      suraVersesNumber: "60",
    ),
    SuraDataModel(
      suraID: "31",
      suraNameAR: "لقمان",
      suraNameEN: "Luqman",
      suraVersesNumber: "34",
    ),
    SuraDataModel(
      suraID: "32",
      suraNameAR: "السجدة",
      suraNameEN: "As-Sajda",
      suraVersesNumber: "30",
    ),
    SuraDataModel(
      suraID: "33",
      suraNameAR: "الأحزاب",
      suraNameEN: "Al-Ahzab",
      suraVersesNumber: "73",
    ),
    SuraDataModel(
      suraID: "34",
      suraNameAR: "سبأ",
      suraNameEN: "Saba",
      suraVersesNumber: "54",
    ),
    SuraDataModel(
      suraID: "35",
      suraNameAR: "فاطر",
      suraNameEN: "Fatir",
      suraVersesNumber: "45",
    ),
    SuraDataModel(
      suraID: "36",
      suraNameAR: "يس",
      suraNameEN: "Ya-Sin",
      suraVersesNumber: "83",
    ),
    SuraDataModel(
      suraID: "37",
      suraNameAR: "الصافات",
      suraNameEN: "As-Saffat",
      suraVersesNumber: "182",
    ),
    SuraDataModel(
      suraID: "38",
      suraNameAR: "ص",
      suraNameEN: "Sad",
      suraVersesNumber: "88",
    ),
    SuraDataModel(
      suraID: "39",
      suraNameAR: "الزمر",
      suraNameEN: "Az-Zumar",
      suraVersesNumber: "75",
    ),
    SuraDataModel(
      suraID: "40",
      suraNameAR: "غافر",
      suraNameEN: "Ghafir",
      suraVersesNumber: "85",
    ),
    SuraDataModel(
      suraID: "41",
      suraNameAR: "فصّلت",
      suraNameEN: "Fussilat",
      suraVersesNumber: "54",
    ),
    SuraDataModel(
      suraID: "42",
      suraNameAR: "الشورى",
      suraNameEN: "Ash-Shura",
      suraVersesNumber: "53",
    ),
    SuraDataModel(
      suraID: "43",
      suraNameAR: "الزخرف",
      suraNameEN: "Az-Zukhruf",
      suraVersesNumber: "89",
    ),
    SuraDataModel(
      suraID: "44",
      suraNameAR: "الدّخان",
      suraNameEN: "Ad-Dukhan",
      suraVersesNumber: "59",
    ),
    SuraDataModel(
      suraID: "45",
      suraNameAR: "الجاثية",
      suraNameEN: "Al-Jathiya",
      suraVersesNumber: "37",
    ),
    SuraDataModel(
      suraID: "46",
      suraNameAR: "الأحقاف",
      suraNameEN: "Al-Ahqaf",
      suraVersesNumber: "35",
    ),
    SuraDataModel(
      suraID: "47",
      suraNameAR: "محمد",
      suraNameEN: "Muhammad",
      suraVersesNumber: "38",
    ),
    SuraDataModel(
      suraID: "48",
      suraNameAR: "الفتح",
      suraNameEN: "Al-Fath",
      suraVersesNumber: "29",
    ),
    SuraDataModel(
      suraID: "49",
      suraNameAR: "الحجرات",
      suraNameEN: "Al-Hujurat",
      suraVersesNumber: "18",
    ),
    SuraDataModel(
      suraID: "50",
      suraNameAR: "ق",
      suraNameEN: "Qaf",
      suraVersesNumber: "45",
    ),
    SuraDataModel(
      suraID: "51",
      suraNameAR: "الذاريات",
      suraNameEN: "Adh-Dhariyat",
      suraVersesNumber: "60",
    ),
    SuraDataModel(
      suraID: "52",
      suraNameAR: "الطور",
      suraNameEN: "At-Tur",
      suraVersesNumber: "49",
    ),
    SuraDataModel(
      suraID: "53",
      suraNameAR: "النجم",
      suraNameEN: "An-Najm",
      suraVersesNumber: "62",
    ),
    SuraDataModel(
      suraID: "54",
      suraNameAR: "القمر",
      suraNameEN: "Al-Qamar",
      suraVersesNumber: "55",
    ),
    SuraDataModel(
      suraID: "55",
      suraNameAR: "الرحمن",
      suraNameEN: "Ar-Rahman",
      suraVersesNumber: "78",
    ),
    SuraDataModel(
      suraID: "56",
      suraNameAR: "الواقعة",
      suraNameEN: "Al-Waqi'a",
      suraVersesNumber: "96",
    ),
    SuraDataModel(
      suraID: "57",
      suraNameAR: "الحديد",
      suraNameEN: "Al-Hadid",
      suraVersesNumber: "29",
    ),
    SuraDataModel(
      suraID: "58",
      suraNameAR: "المجادلة",
      suraNameEN: "Al-Mujadila",
      suraVersesNumber: "22",
    ),
    SuraDataModel(
      suraID: "59",
      suraNameAR: "الحشر",
      suraNameEN: "Al-Hashr",
      suraVersesNumber: "24",
    ),
    SuraDataModel(
      suraID: "60",
      suraNameAR: "الممتحنة",
      suraNameEN: "Al-Mumtahina",
      suraVersesNumber: "13",
    ),
    SuraDataModel(
      suraID: "61",
      suraNameAR: "الصف",
      suraNameEN: "As-Saff",
      suraVersesNumber: "14",
    ),
    SuraDataModel(
      suraID: "62",
      suraNameAR: "الجمعة",
      suraNameEN: "Al-Jumu'a",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraID: "63",
      suraNameAR: "المنافقون",
      suraNameEN: "Al-Munafiqun",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraID: "64",
      suraNameAR: "التغابن",
      suraNameEN: "At-Taghabun",
      suraVersesNumber: "18",
    ),
    SuraDataModel(
      suraID: "65",
      suraNameAR: "الطلاق",
      suraNameEN: "At-Talaq",
      suraVersesNumber: "12",
    ),
    SuraDataModel(
      suraID: "66",
      suraNameAR: "التحريم",
      suraNameEN: "At-Tahrim",
      suraVersesNumber: "12",
    ),
    SuraDataModel(
      suraID: "67",
      suraNameAR: "الملك",
      suraNameEN: "Al-Mulk",
      suraVersesNumber: "30",
    ),
    SuraDataModel(
      suraID: "68",
      suraNameAR: "القلم",
      suraNameEN: "Al-Qalam",
      suraVersesNumber: "52",
    ),
    SuraDataModel(
      suraID: "69",
      suraNameAR: "الحاقة",
      suraNameEN: "Al-Haqqah",
      suraVersesNumber: "52",
    ),
    SuraDataModel(
      suraID: "70",
      suraNameAR: "المعارج",
      suraNameEN: "Al-Ma'arij",
      suraVersesNumber: "44",
    ),
    SuraDataModel(
      suraID: "71",
      suraNameAR: "نوح",
      suraNameEN: "Nuh",
      suraVersesNumber: "28",
    ),
    SuraDataModel(
      suraID: "72",
      suraNameAR: "الجن",
      suraNameEN: "Al-Jinn",
      suraVersesNumber: "28",
    ),
    SuraDataModel(
      suraID: "73",
      suraNameAR: "المزّمّل",
      suraNameEN: "Al-Muzzammil",
      suraVersesNumber: "20",
    ),
    SuraDataModel(
      suraID: "74",
      suraNameAR: "المدّثر",
      suraNameEN: "Al-Muddathir",
      suraVersesNumber: "56",
    ),
    SuraDataModel(
      suraID: "75",
      suraNameAR: "القيامة",
      suraNameEN: "Al-Qiyamah",
      suraVersesNumber: "40",
    ),
    SuraDataModel(
      suraID: "76",
      suraNameAR: "الإنسان",
      suraNameEN: "Al-Insan",
      suraVersesNumber: "31",
    ),
    SuraDataModel(
      suraID: "77",
      suraNameAR: "المرسلات",
      suraNameEN: "Al-Mursalat",
      suraVersesNumber: "50",
    ),
    SuraDataModel(
      suraID: "78",
      suraNameAR: "النبأ",
      suraNameEN: "An-Naba'",
      suraVersesNumber: "40",
    ),
    SuraDataModel(
      suraID: "79",
      suraNameAR: "النازعات",
      suraNameEN: "An-Nazi'at",
      suraVersesNumber: "46",
    ),
    SuraDataModel(
      suraID: "80",
      suraNameAR: "عبس",
      suraNameEN: "Abasa",
      suraVersesNumber: "42",
    ),
    SuraDataModel(
      suraID: "81",
      suraNameAR: "التكوير",
      suraNameEN: "At-Takwir",
      suraVersesNumber: "29",
    ),
    SuraDataModel(
      suraID: "82",
      suraNameAR: "الإنفطار",
      suraNameEN: "Al-Infitar",
      suraVersesNumber: "19",
    ),
    SuraDataModel(
      suraID: "83",
      suraNameAR: "المطفّفين",
      suraNameEN: "Al-Mutaffifin",
      suraVersesNumber: "36",
    ),
    SuraDataModel(
      suraID: "84",
      suraNameAR: "الإنشقاق",
      suraNameEN: "Al-Inshiqaq",
      suraVersesNumber: "25",
    ),
    SuraDataModel(
      suraID: "85",
      suraNameAR: "البروج",
      suraNameEN: "Al-Buruj",
      suraVersesNumber: "22",
    ),
    SuraDataModel(
      suraID: "86",
      suraNameAR: "الطارق",
      suraNameEN: "At-Tariq",
      suraVersesNumber: "17",
    ),
    SuraDataModel(
      suraID: "87",
      suraNameAR: "الأعلى",
      suraNameEN: "Al-A'la",
      suraVersesNumber: "19",
    ),
    SuraDataModel(
      suraID: "88",
      suraNameAR: "الغاشية",
      suraNameEN: "Al-Ghashiyah",
      suraVersesNumber: "26",
    ),
    SuraDataModel(
      suraID: "89",
      suraNameAR: "الفجر",
      suraNameEN: "Al-Fajr",
      suraVersesNumber: "30",
    ),
    SuraDataModel(
      suraID: "90",
      suraNameAR: "البلد",
      suraNameEN: "Al-Balad",
      suraVersesNumber: "20",
    ),
    SuraDataModel(
      suraID: "91",
      suraNameAR: "الشمس",
      suraNameEN: "Ash-Shams",
      suraVersesNumber: "15",
    ),
    SuraDataModel(
      suraID: "92",
      suraNameAR: "الليل",
      suraNameEN: "Al-Lail",
      suraVersesNumber: "21",
    ),
    SuraDataModel(
      suraID: "93",
      suraNameAR: "الضحى",
      suraNameEN: "Ad-Duha",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraID: "94",
      suraNameAR: "الشرح",
      suraNameEN: "Ash-Sharh",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraID: "95",
      suraNameAR: "التين",
      suraNameEN: "At-Tin",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraID: "96",
      suraNameAR: "العلق",
      suraNameEN: "Al-Alaq",
      suraVersesNumber: "19",
    ),
    SuraDataModel(
      suraID: "97",
      suraNameAR: "القدر",
      suraNameEN: "Al-Qadr",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraID: "98",
      suraNameAR: "البينة",
      suraNameEN: "Al-Bayyina",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraID: "99",
      suraNameAR: "الزلزلة",
      suraNameEN: "Az-Zalzalah",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraID: "100",
      suraNameAR: "العاديات",
      suraNameEN: "Al-Adiyat",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraID: "101",
      suraNameAR: "القارعة",
      suraNameEN: "Al-Qari'a",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraID: "102",
      suraNameAR: "التكاثر",
      suraNameEN: "At-Takathur",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraID: "103",
      suraNameAR: "العصر",
      suraNameEN: "Al-Asr",
      suraVersesNumber: "3",
    ),
    SuraDataModel(
      suraID: "104",
      suraNameAR: "الهمزة",
      suraNameEN: "Al-Humazah",
      suraVersesNumber: "9",
    ),
    SuraDataModel(
      suraID: "105",
      suraNameAR: "الفيل",
      suraNameEN: "Al-Fil",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraID: "106",
      suraNameAR: "قريش",
      suraNameEN: "Quraysh",
      suraVersesNumber: "4",
    ),
    SuraDataModel(
      suraID: "107",
      suraNameAR: "الماعون",
      suraNameEN: "Al-Ma'un",
      suraVersesNumber: "6",
    ),
    SuraDataModel(
      suraID: "108",
      suraNameAR: "الكوثر",
      suraNameEN: "Al-Kawthar",
      suraVersesNumber: "3",
    ),
    SuraDataModel(
      suraID: "109",
      suraNameAR: "الكافرون",
      suraNameEN: "Al-Kafirun",
      suraVersesNumber: "6",
    ),
    SuraDataModel(
      suraID: "110",
      suraNameAR: "النصر",
      suraNameEN: "An-Nasr",
      suraVersesNumber: "3",
    ),
    SuraDataModel(
      suraID: "111",
      suraNameAR: "المسد",
      suraNameEN: "Al-Masad",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraID: "112",
      suraNameAR: "الإخلاص",
      suraNameEN: "Al-Ikhlas",
      suraVersesNumber: "4",
    ),
    SuraDataModel(
      suraID: "113",
      suraNameAR: "الفلق",
      suraNameEN: "Al-Falaq",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraID: "114",
      suraNameAR: "الناس",
      suraNameEN: "An-Nas",
      suraVersesNumber: "6",
    ),
  ];
}
